# Generated by Django 4.1.5 on 2023-05-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0002_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
