# Generated by Django 4.1.5 on 2023-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0004_alter_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="private_key",
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_key",
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
