# Generated by Django 4.1.5 on 2023-05-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message_app", "0006_remove_userprofile_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection",
                    models.TextField(default=None, max_length=250, null=True),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_one",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_two",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
