# Generated by Django 4.1.5 on 2023-05-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0007_connections"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="friends",),
        migrations.RemoveField(model_name="userprofile", name="group_key",),
        migrations.AddField(
            model_name="userprofile",
            name="private_key",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="public_key",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
