# Generated by Django 4.1.5 on 2023-05-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_app", "0008_remove_userprofile_friends_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="private_key",),
        migrations.RemoveField(model_name="userprofile", name="public_key",),
        migrations.DeleteModel(name="Connections",),
    ]
