# Generated by Django 4.1.7 on 2023-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0009_remove_userprofile_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
